### ISSUE TITLE
Don't delete XComGame/Published by default in `clean` task

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2ModBuildCommon#36]
As much as it is needed for a full `clean`, I think it's not something that should happen as a result of running `clean` for the Community Promotion Screen for example. I predict myself cursing quite a bit if this version of the clean task ends up in several other projects and removes `Published` regularly because copying TFCs actually takes ages.

**Comment by Xymanek** [comment]
Perhaps #18 is a better approach? It would support both full clean and a localized effect

**Comment by robojumper** [comment]
Right, I forgot about that. The only issue I see there is disk space: Most people have the CHL project on a different drive than the game, and maybe wouldn't expect their project directory to grow by 10GB.

**Comment by Xymanek** [comment]
Considering we are already planning to copy the TFCs over for asset cooking (#10), I think it's just an unfortunate price to pay. We just need to make sure to mention it somewhere prominent

**Comment by robojumper** [comment]
Perhaps a good way to mitigate that would be the addition of an option to override the BuildCache location.

**Comment by Xymanek** [comment]
Good idea, but it would need to be in some untracked file (i.e. not in `build.ps1`)
