### ISSUE TITLE
Don't recommend pulling straight from `main` for adding/updating the subtree

### ISSUE THREAD

**Issue by robojumper** [X2CommunityCore/X2ModBuildCommon#37]
README.md has commands that pull from latest main or recommends downloading the latest sources to copy them into the project. We should instead have a `stable` branch for this purpose wo that the regular installation process can only end up installing a release version, not a development version that may be in flux.

May become obsolete with #25 but that's still a ways off.

**Comment by Xymanek** [comment]
I would suggest instead prompting users to use a specific tag (instead of a branch name)
